const ACTIONS ={
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    ADD_TO_LIST: 'ADD_TO_LIST',
    DELETE_FROM_LIST: 'DELETE_FROM_LIST'
}

export default ACTIONS